### ISSUE TITLE
Handle primary key conflicts better (upserts or ignore)

### ISSUE THREAD

**Issue by proddata** [crate/cratedb-prometheus-adapter#135]
_Originated from community question: https://community.cratedb.com/t/prometheus-failed-to-write-data-into-cratedb-after-encountering-error-a-document-with-the-same-primary-key-exists-already/1724_

---

We probably could add the option to use upserts or make it the even default approach.

Since the table definition is using primary keys we should change the
[insert statement](https://github.com/crate/cratedb-prometheus-adapter/blob/dc5c40f9b87ace1d543bd6cca0d6500884590c49/crate.go#L16)

https://github.com/crate/cratedb-prometheus-adapter/blob/dc5c40f9b87ace1d543bd6cca0d6500884590c49/crate.go#L16

 to either ignore conflicts:

```sql
INSERT INTO metrics ("labels", "labels_hash", "timestamp", "value", "valueRaw") VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ("timestamp", "labels_hash", "day__generated")
DO NOTHING;
```

or handle upserts:

```sql
INSERT INTO metrics ("labels", "labels_hash", "timestamp", "value", "valueRaw") VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ("timestamp", "labels_hash", "day__generated")
DO UPDATE SET
   "value" = excluded."value",
   "valueRaw" = excluded."valueRaw";
```

Potentially this could be configurable (to do either or).

**Comment by surister** [comment]
Maybe adding an environment variable `ON_CONFLICT` with values `ignore` and `upsert` and make `upsert` default?

`docker run -it --rm --publish=9268:9268 -e ON_CONFLICT=ignore ghcr.io/crate/cratedb-prometheus-adapter`

**Comment by amotl** [comment]
The program currently doesn't do much with environment variables, opposed to what one would expect for a cloud-native program. The configuration is mostly handled on behalf of configuration file settings.

Because it is possible to configure multiple CrateDB endpoints there, i.e. the program implements a flavor of multi-tenancy, it is mostly not applicable to use settings that would apply globally.
