### ISSUE TITLE
Investigate how to scale out this service

### ISSUE THREAD

**Issue by hlcianfagna** [crate/cratedb-prometheus-adapter#72]
To avoid a single point of failure and/or handle high loads, it could be interesting to deploy multiple instances of the adapter pointing to the same CrateDB cluster and present them to Prometheus with a load balancer.
This ticket is to document if this is possible or not.

**Comment by amotl** [comment]
Hi there,

on this matter, I have been able to gather some important bits of information, where people may run into problems.

> If [we|they] have a lot of things going on in Prometheus, the connections to CrateDB are not freed up quickly enough, so the requests are queued and eventually run into timeout situations. [We|they] assume the bottleneck is this service and not CrateDB behind.

With kind regards,
Andreas.

**Comment by amotl** [comment]
A few things come to mind on this topic.

> 1. If there a lot of things going on in Prometheus.

What ballpark figure is "a lot of" in this case?

> 2. The service is using up all the `max_connections`.

It looks like the default setting is 5. That's not much for a high-performance/-traffic scenario, so I believe it would be good to raise that number already, and check how that improves the situation.

> `max_connections: 5`
> -- https://github.com/crate/cratedb-prometheus-adapter#cratedb-adapter-endpoint-configuration

**Comment by amotl** [comment]
Hi again,

I am starting to investigate the details of the corresponding data shoveling routines, and want to report about its outcome.

> The write path implementation to CrateDB looks pretty efficient. `MaxConnections` is actually the maximum connection pool size for a `pgx` connection pool. Communication uses batched requests, so there is probably no way to do it better.
>
> -- https://github.com/crate/cratedb-prometheus-adapter/blob/0.4.0/crate.go#L91-L130

With kind regards,
Andreas.

**Comment by amotl** [comment]
My thoughts are those. Let me know what you think about it, and if more things come to mind.

### a) Verify chunking
Efficiency, specifically for leveraging the »batched requests« method optimally, can only be assumed if chunking [1] is performed properly, see also my other recent patch to the Python driver. I think CrateDB Prometheus Adapter does not do any chunking on its own, but assumes the data to arrive in chunks already, as outlined at [2].

In order to be able to give any advises, we would need to know about the typical sizes of those chunks in common Prometheus environments, or specifically at the site where this service observes bottleneck situations.

[1] https://en.wikipedia.org/wiki/Chunking_(computing)
[2] https://github.com/crate/cratedb-prometheus-adapter/blob/0.4.0/server_test.go#L179-L185

### b) Add re-chunking
When chunk sizes are too small, this will indeed be the bottleneck in a busy system. In order to improve the situation, we'd have to apply some re-chunking, in order to feed the outbound insert operation batcher better.

### c) Increase maximum connection pool size
As outlined above, raising the the number of pool workers above the default value may improve the situation already. However, please note it does not magically resolve any other shortcomings.

### d) Use two different connection pools
In order to offer better configuration and runtime options, we may adjust the implementation so that each data channel (read vs. write) uses its own connection pool.

**Comment by amotl** [comment]
> it could be interesting to deploy multiple instances of the adapter pointing to the same CrateDB cluster

Currently, none of the items enumerated above indicates that the proposal, to deploy multiple instances, would help in any way to improve processing efficiency and performance. I think it may even make the situation worse.

**Comment by hlcianfagna** [comment]
I tested a scaled-out deployment with
prometheus-node-exporter --> prometheus --> haproxy --> 2 x cratedb-prometheus-adapter --> CrateDB 
and it worked perfectly both for reads and writes

**Comment by amotl** [comment]
Hi again,

as already evaluated within this discussion, I don't think scaling out this service helps to address the observed flaws, and adds additional infrastructure, which will raise the complexity of the whole setup.

Instead, the implementation had to be improved to be ready for production use scenarios. Those patches will do that already, a corresponding summary with more details has been added at [^1].

- GH-80
- GH-81

With kind regards,
Andreas.

[^1]: https://community.crate.io/t/cratedb-prometheus-adapter-croaks-with-err-context-deadline-exceeded/376/16

**Comment by hlcianfagna** [comment]
Thank you Andreas. With the effort you have put on those 2 PRs and the test I did in https://github.com/crate/cratedb-prometheus-adapter/issues/72#issuecomment-1645738781 I think we can go ahead and consider this issue resolved.

**Comment by surister** [comment]
Closing as it seems to be resolved, reopen if necessary.
